### PR TITLE
Update config implementation, add support for private leagues

### PR DESCRIPTION
**Pull request by voicelessreason**
Hey u/Drippyer! I came up with some stuff that I think improves what you've started, I hope you don't mind! Happy to discuss and tweak my suggestions if you've got ideas of how to make them even better. Basically what I've done is I've pulled the config out of the main script so people don't have to touch that at all and I've added a config file to the project that people can fill out instead (this involved introducing an additional dependency on pyyaml). I've also added support for private leagues and filled out the readme with some info that will help people get going quicker. 

Let me know what you think!

### CODE REVIEW

**Comment by drippyer** [comment]
Hey there, sorry for the lack of response, been busy with some personal stuff. I love what you've added, especially because it addresses the two key points I wanted to focus on! I have already added a user config file however, one that is just loaded in another python file to avoid loading another library.

Glad you got private leagues working though! I hadn't focused near enough time on it so it's good to see you were able to do so.

Admittedly, I'm not familiar enough with git to know how to merge some parts of a commit, but I'm going to see what I can do lol

Thanks for being interested and contributing!

**Comment by voicelessreason** [comment]
Ah, interesting, I'm not too familiar with how python does file dependencies so I went with yaml since that's what I was comfortable with...let me go ahead and pull your latest changes and I'll update my changes to rely on the config file you created. 

I've made a number of other changes in my own repo that rely on the config file I created so I'll see if I can find a happy middle ground that doesn't break your stuff or mine. Shouldn't be too tricky.

I also took a shot at implementing projections but what I found is that the player projection points available in the API do not update real time so sadly the best I could get was showing the original projection for a team rather than the updated value throughout the game.

**Comment by drippyer** [comment]
I just updated to reflect a similar style to what you were accomplishing with yaml. Feel free to pull my latest commit from the master branch, I think I merged everything properly.

Hopefully I haven't broken anything you changed, ideally it's just ensuring variables names align!

I also found the exact same thing regarding projections though, so I've started diving into the actual API rather than cwendt's wrapper.

**Comment by voicelessreason** [comment]
Oh nice, thanks for doing that! I'll take a look tonight when I'm done with work stuff and see if there's anything out of whack, and push up any changes necessary. 

I think there probably is data in the actual api somewhere that could help us get the real time projections, but I'm not sure where they stick it. Maybe in the underlying class for box_score, since they don't actually update the player projection points. Let me know if you find anything out!

I also have some changes on my repo (in roundup-scripts branch) for generating some commissioner reports if that's something that interests you, but that's still a bit of a WIP :)

**Comment by drippyer** [comment]
No problem lol, I tried to keep it similar to your while following the naming scheme I normally use. There are definitely some variable name discrepancies but it doesn't look terribly daunting.

I do think you're right about there being more info hidden in the true API though, there seems to be an attribute called box_player according to various documentations but I can't seem to find it myself. I'm guessing that could have that info in it but obviously no way to tell until we crack that nut hahah.

I will definitely be taking a look at those reports, I've been itching for a new angle on the tool!

**Comment by drippyer** [comment]
Just realized cwendt updated his API from a PR from someone else that automatically pulls swid and espn_s2 using username and password. Didn't realize it was a recent addition but now it is even more user-friendly.

**Comment by voicelessreason** [comment]
Have you been able to authenticate with the user/pass combo? So far I'm hitting access denied when trying to use it though perhaps I'm doing something incorrectly.

**Comment by voicelessreason** [comment]
Oh nvm, it just needs email address and not username, that was my issue.

**Comment by voicelessreason** [comment]
Yeah I nvm again, the new auth is still broken for me but I'm working with cwendt on whats going wrong. Really confusing error since I can still auth with swid and s2 just fine, and it even appears as if I get past auth and then fail on actually making the request to the API. Really curious if you can confirm this is working for you bc I'm at a loss haha.

**Comment by drippyer** [comment]
Oof, no I’m not aware of that :/

The only reason this didn’t have private league capabilities in the beginning was because I am LM in 2 of my leagues and the last one was public by default for some reason. So I haven’t needed to log in with it unfortunately...

I’ll see if I can’t make a new private league later today and try to do some messing around with it myself.

Sucks you’re running into this issue but I’m sure all of us will eventually get to the bottom of this lol

**Pull request closed without merging**
