### PR TITLE
Add original projection to scoreboard, add roundup report

### PR DESCRIPTION
**Pull request by voicelessreason**
This PR adds the projected score for each team to the score. Also adds roundup report to menu and adds supporting methods.

I'm open to any changes you might have for these...its currently formatted in such a way to facilitate posting to slack or somewhere else that treats * as bold.

### CODE REVIEW

**Comment by drippyer** [comment]
All of this is awesome!!
Might be important to note that the projected score is the initial projection and doesn't update like FantasyCast does. I can add this myself because it's such a minor change. 
I added this PR as a branch and will be looking through it a bit to add PrettyTables to the reports. I like to keep it as narrow as possible while still getting the info across cleanly so that it could be run from a cell phone for example lol.
Thanks so much for the contribution!

**Comment by drippyer** [comment]
This has been largely incorporated into the add-weekly-reports branch: https://github.com/drippyer/ESPN_FF_Tool/tree/add-weekly-reports

Thank you so much for the time and effort you put into this!

I'd love for you to go through and see what you think of my adjustments to fit in with the look of the rest of the script.

I removed the format home and away teams functions because it removed the ability to color your score based on whether you were winning or losing. I also added functions that allow for easier text coloring because it was annoying me. Last thing I added was a getLeagues() function that can be called to connect to a league in fewer lines of code across the project.

Let me know what you think!

**Comment by voicelessreason** [comment]
Interesting, I did not realize that the scoreboard was attempting to set the color based on who was winning, my assumption was that you had set the current users team as the green team, so that's why I accidentally blew away that functionality. Whoops! I'll make a new PR to fix those methods such that they preserve the original behavior. I do think it will be really nice to refactor the row formatting out of the main method for maintainability and readability reasons, but if you've already written methods to simplify the coloring that might be good enough for now.

Other than that, I realize in retrospect that it would've been more useful to just create the methods in roundup-scripts such that they spit out the data instead of formatting for my needs. I'll take a look at what you have and see if I have any worthwhile suggestions, then I'll probably just write a separate method for formatting that data and keep it on my own branch...that probably makes more sense from a mass use perspective.

I was thinking about refactoring the auth stage into a getLeague (similar to the method I originally had before the auth update) so I'll take a look at what you have! One thing I wanted to get to in the near future was making it such that the roundup scripts only connected once rather than once per method, since that would improve performance significantly

**Comment by voicelessreason** [comment]
@drippyer I know this is two years after the fact, but football starts tonight and so I started thinking about this project again and looked back to find your comment. I took a look at the branch you posted and it looks good to me! The only suggestion I would have (and this was actually a mistake by me, not by you porting the code) is that I think the barnburner and snoozefest functions should include the matchup names similar to how the blowout and nailbiter methods do. I'd be happy to make a PR to implement this after your main branch is merged.

I was thinking about abstracting the login portion of the tool into an initial call to the API that saves all the leagues from config in an initialization function, as it would save us from a lot of repeated execution.

Which brings me to the topic of authorization...there is currently no way to access private leagues without using swid and espn_s2, and so I was thinking it might be a good idea to update the tool such that it assumes this authentication method instead, similar to how cwendt94's project is [deprecating user/pass auth](https://github.com/cwendt94/espn-api#readme). Thoughts?

**Comment by voicelessreason** [comment]
[Here is what I was thinking in terms of updating the league authorization](https://github.com/voicelessreason/ESPN_FF_Tool/pull/2/files), though obviously this was written without the latest changes you've proposed in add-weekly-report branch so it would need to be updated....but I think storing the config in a dict and then using a single initialization (rather than repeatedly hitting the API on each method call) would be much more efficient than the getLeague function which will sometimes pull data that we don't always need. It would probably also be a good idea to update the readme to include instructions on grabbing the SWID and espn_s2 since some people might not know what those are.

**Pull request closed without merging**
